# Android SDK CI
name: CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
      # Set up Java
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      # Build
      - uses: eskatos/gradle-command-action@v1
        with:
            arguments: build
            distributions-cache-enabled: true
            dependencies-cache-enabled: true
            configuration-cache-enabled: true

      # Run unit tests
      - uses: eskatos/gradle-command-action@v1
        with:
            arguments: testDebugUnitTest
            distributions-cache-enabled: true
            dependencies-cache-enabled: true
            configuration-cache-enabled: true
